name: vds-blueprint-bazzite
on:
  #schedule:
  #  - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'README.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'config/recipe.yml'
          registry_token: ${{ github.token }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          prune: true
